services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    IDCI\Bundle\SAMClientBundle\:
        resource: '../src/*'
        exclude: '../../{Model}'

    IDCI\Bundle\SAMClientBundle\Client\SAMApiClient:
        arguments:
            $logger: '@logger'
            $clientId: '%idci_sam_client.client_id%'
            $clientSecret: '%idci_sam_client.client_secret%'
            $mode: '%idci_sam_client.mode%'
